[Android] Explicitly specified headers for GURL Needed to avoid build errors like
../../brave/browser/android/preferences/brave_pref_service_bridge.cc:56:7: error: invalid use of incomplete type 'GURL'